version: "3.6"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  tax-fix-exercise:
    container_name: tax-fix-exercise
    restart: always
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo